engines:
    fixme:
        enabled: true
    phpmd:
        enabled: true
ratings:
    paths:
        - "**.php"
exclude_paths:
    - "bootstrap/*"
    - "config/*"
    - "database/*"
    - "docker/*"
    - "public/*"
    - "storage/*"
