engines:
    fixme:
        enabled: true
    phpmd:
        enabled: true
        checks:
            CleanCode/StaticAccess:
                enabled: false
            Naming/LongVariable:
                enabled: false
            Naming/ShortVariable:
                enabled: false
ratings:
    paths:
        - "**.php"
exclude_paths:
    - "bootstrap/*"
    - "config/*"
    - "database/*"
    - "platform/*"
    - "public/*"
    - "storage/*"
    - "tests/*"
