version: '2'
services:
  data:
    image: impactbot/impact-platform-data
    volumes:
      - ./:/data/www

  php:
      image: impactbot/impact-platform-phpfpm
      volumes_from:
        - data
      ports:
        - "9000:9000"
      depends_on:
        - memcached
        - redis
      command:
        - php-fpm
        - -F

  memcached:
    image: impactbot/impact-platform-memcached
    ports:
      - "11211:11211"
    env_file:
      - docker/env/.env.dev

  nginx:
    image: impactbot/impact-platform-nginx
    volumes_from:
      - data
    ports:
      - "80:80"
      - "443:443"
    links:
      - php:php
      - redis:redis
      - data:data
    volumes:
      - ./docker/ssl/:/data/config/ssl
      - ./docker/sites/:/data/config/sites

  redis:
    image: impactbot/impact-platform-redis
    ports:
      - "6379:6379"

  composer:
    image: impactbot/impact-platform-composer
    volumes_from:
      - data

  artisan:
    image: impactbot/impact-platform-php
    volumes_from:
      - data
    depends_on:
      - memcached
    entrypoint:
      - php
      - artisan
