data:
  image: impactbot/impact-platform-data
  volumes:
    - ./:/data/www

php:
  image: impactbot/impact-platform-phpfpm
  volumes_from:
    - data
  ports:
    - "9000:9000"
  links:
    - memcached:memcached
    - redis:redis

memcached:
  image: impactbot/impact-platform-memcached
  ports:
    - "11211:11211"
  env_file:
    - docker/env/.env.dev

nginx:
  image: impactbot/impact-platform-nginx
  volumes_from:
    - data
  ports:
    - "80:80"
    - "443:443"
  links:
    - php:php
    - redis:redis
  volumes:
    - ./docker/ssl/:/data/config/ssl
    - ./docker/sites/:/data/config/sites

redis:
  image: impactbot/impact-platform-redis
  ports:
    - "6379:6379"

artisan:
  image: impactbot/impact-platform-artisan
  volumes_from:
    - data
  links:
    - redis:redis
    - memcached:memcached
  env_file:
    - docker/env/.env.dev

composer:
  image: impactbot/impact-platform-composer
  volumes_from:
    - data
